### ISSUE TITLE
Refactor of Virtual Destructor Incorrect

### ISSUE THREAD

**Issue by rmerriam** [Cevelop/Issues#34] opened 2017-06-21 17:14 UTC
Starting with the destructor:

`    virtual ~TaskStatus() override = default;
`
the suggestion is to add "noexcept". Accepting this change results in:

`virtual ~TaskStatus() override noexcept override = default;
`

Cevelop 1.7.1
GCC 4.9
Ubuntu 14.04.5

**Comment by tcorbat** [comment] 2017-06-22 07:31
Thanks for this report as well! I reproduced the issue. I'll have to figure out whether the problem is within our code or whether it has to be fixed in Eclipse CDT (which might take longer until the next release, as it is too late for Oxygen).

**Comment by tcorbat** [comment] 2017-06-22 11:31
As I thought this issue occurs due to a bug in CD [1]. I'll fix it there and we will have it with one of the next releases (probably with CDT 9.3.1).

[1] https://bugs.eclipse.org/bugs/show_bug.cgi?id=518628

**Comment by rmerriam** [comment] 2017-06-23 02:57
Since you're tied into the CDT work I'll mention this problem. Inside a class define:

virtual func() override {}

Do a ctrl-t to make it an inline in the header and the override is carried along.

**Comment by tcorbat** [comment] 2017-06-23 06:01
Right, thanks for mentioning it. This has already been reported [1]. I'll have a look at it.

[1] https://bugs.eclipse.org/bugs/show_bug.cgi?id=518273

**Comment by Darnor** [comment] 2019-08-06 09:47
Both upstream bugs have been fixed quite a while ago, so I'll assume this issue resolved.

**Closed as completed by Darnor** 2019-08-06 09:47 UTC
Labels: bug
