### ISSUE TITLE
Refactor of Constructor to use std::string looses default value

### ISSUE THREAD

**Issue by rmerriam** [Cevelop/Issues#35] opened 2017-06-21 17:20 UTC
Starting with the constructor (or any method):

`     explicit HarnessStatus(const char* const msg = "/srcsim/finals/harness");
`
the refactor to using std::string results in:

`     explicit HarnessStatus(const std::string& msg);
     explicit HarnessStatus(const char* const msg = "/srcsim/finals/harness");
`
The default value for the string is lost and a duplicate constructor is created. The duplicate may cause confusion with signature matching for the compiler. 

The duplicate also does not contain any code from the original constructor or method. This is very disruptive.

**Comment by tcorbat** [comment] 2017-06-22 07:37
This behavior is indeed strange. It also happens for other member and non-member functions. We'll look into that.

**Comment by tonisuter** [comment] 2017-06-23 13:03
Thanks for the bug report! Currently, this refactoring only works with functions that contain a null-check for the C-string parameter. It will then generate a duplicate of the function with a `std::string` parameter and delegate to that function if the string is not null. Here's an example:

```cpp
#include <iostream>

void login(const char *pw) {
    if(!pw) {
        std::cout << "missing password!\n";
        return;
    }

    if(strcmp(pw, "123456") == 0) {
        std::cout << "login successful!\n";
    } else {
        std::cout << "wrong password!\n";
    }
}

int main() {
    login(nullptr);		// missing password!
    login("password");	    // wrong password!
    login("123456");	    // login successful!
}
```

```cpp
#include <iostream>
#include <string>

void login(const std::string& pw) {
    if (pw == "123456") {
        std::cout << "login successful!\n";
    } else {
        std::cout << "wrong password!\n";
    }
}

void login(const char *pw) {
    if(!pw) {
        std::cout << "missing password!\n";
        return;
    }
    login(std::string(pw));
}

int main() {
    login(nullptr);		// missing password!
    login("password");	    // wrong password!
    login("123456");		// login successful!
}
```

Anyway, I fixed this issue on the master branch and the fix will be part of the next Cevelop release.

**Closed as completed by tonisuter** 2017-06-23 13:03 UTC
Labels: bug, charwars
