### ISSUE TITLE
Code analysis raises lots of null pointer exceptions

### ISSUE THREAD

**Issue by aacirino** [Cevelop/Issues#59] opened 2017-11-03 14:00 UTC
I've attached the log file.

My system
macOS 10.11.6 El Capitan
Cevelop Version: 1.8.0-201707131430

[log.zip](https://github.com/Cevelop/Issues/files/1441256/log.zip)

**Comment by Darnor** [comment] 2017-11-10 15:56
Do you have any code snippets for which the exceptions arise? This would help us greatly in pinpointing the issues.

**Comment by aacirino** [comment] 2017-11-27 17:39
Any code will trigger the exceptions. For instance, a newly created C++ project with the template for "Hello World" triggers the exceptions. I've again attached a log file and my installation details as supplied by Cevelop.
[files.zip](https://github.com/Cevelop/Issues/files/1506932/files.zip)

**Comment by Darnor** [comment] 2017-11-28 17:27
I've just checked with my local version and I am unable to reproduce these errors. Do you have the newest version of the plug-ins installed?

We're also working on a new release which should hopefully fix some of these issues as well.

**Comment by aacirino** [comment] 2017-11-28 17:42
Hi, I update my installation almost everyday

**Comment by Darnor** [comment] 2017-12-13 13:55
An update for the beta plug-ins should now be available which should fix most of the exceptions found in your log. There's also an update available for the SConsolidator (https://github.com/ifs-hsr/SConsolidator) which fixes another error. Thank you very much for reporting. 👍

**Comment by aacirino** [comment] 2017-12-13 18:05
Hi Darnor, the updated plug-ins indeed fixed the exceptions. The SConsolidator issue remains and the update site doesn't seen to have a new version. I am only able to use LLVM with scons by an import in SConstruct like `MySConfig.py` with the options (for instance)
`CXX_FLAGS=' -emit-llvm -Wall -c -fmessage-length=0 -std=c++17'`
`COMPILER_NAME='/usr/local/bin/ccache /usr/local/opt/llvm/bin/clang++'`
But I think this talk about SConsolidator should be in the thread about it.

**Comment by Darnor** [comment] 2017-12-18 13:56
Thank you for your feedback. I'm closing this issue then and let https://github.com/Cevelop/Issues/issues/58 open for the SConsolidator issue.

**Closed as completed by Darnor** 2017-12-18 13:56 UTC
