### ISSUE TITLE
1.7 Release

### ISSUE THREAD

**Issue by misto** [Cevelop/Issues#17] opened 2017-03-30 07:16 UTC
Which plugins are ready?

- [x] CUTE Plugin
- [x] CharWars
- [x] Elevator
- [x] Elevenator
- [x] Macronator
- [x] Namespactor
- [x] CloneWar
- [x] Includator
- [x] Constificator
- [x] Templator
- [x] Intwidthfixator
- [x] GSLator
- [x] Mockator
- [x] Sconsolidator

We also need to update:

- [x] Website
- [ ] Arch Linux
- [x] Brew
  - [x] OSX Signing

**Comment by misto** [comment] 2017-03-30 07:17
@tcorbat @tonisuter @fmorgner @Stautob bitte die Liste der Plug-ins ergänzen (habs nur von letztem Mal kopiert)

**Comment by fmorgner** [comment] 2017-04-07 10:53
All 'CUTE' plugins should be ready and tagged for release. The 'Cevelop Plug-ins' are also ready and tagged. AFAIK @Stautob's Intwidthfixator will remain in the optional track for the foreseeable future. GSLator is scheduled to remain optional for the 1.7.0 release.

**Comment by misto** [comment] 2017-04-07 11:00
Does anybody know the state of Mockator and Sconsolidator? I guess Sconsolidator is pretty stable..

**Comment by tcorbat** [comment] 2017-04-07 11:52
Shall we use CDT 9.2.2 for Cevelop 1.7?

**Comment by misto** [comment] 2017-04-07 12:14
Does it include all patches we shipped in the past releases?

**Comment by rtosman** [comment] 2017-04-13 21:13
cevelop 1.7 fails to load on Windows 10 Creators Update with Java 8.

The error is:

![image](https://cloud.githubusercontent.com/assets/6283239/25024596/5e74049a-2053-11e7-844c-60012b4b6bd0.png)

**Comment by tcorbat** [comment] 2017-04-14 06:45
Do you have the correct version of Java? 64bit for 64bit System and Cevelop
64 bit?

This might also help:
http://stackoverflow.com/questions/18609160/eclipse-returns-error-message-java-was-started-but-returned-exit-code-1


On Apr 13, 2017 11:13 PM, "rtosman" <notifications@github.com> wrote:

cevelop 1.7 fails to load on Windows 10 Creators Update with Java 8.

The error is:

[image: image]
<https://cloud.githubusercontent.com/assets/6283239/25024596/5e74049a-2053-11e7-844c-60012b4b6bd0.png>

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/Cevelop/Issues/issues/17#issuecomment-294023169>, or mute
the thread

**Comment by rtosman** [comment] 2017-04-14 16:58
@tcorbat Thanks! That was it, somehow the Java installer had resisted all attempts I made to install the 64 bit version and had installed the 32 bit version.  Sorry, I have been out of the Java stream of consciousness for several years :-)

**Comment by rtosman** [comment] 2017-04-14 23:32
So, after trying to analyze our rather large source base, I keep getting Java null pointer exceptions:

Example:

Failed to get including location of include float.h.
Failed to get including location of include limits.h.
Failed to get including location of include math.h.
Failed to get including location of include new.
Failed to get including location of include stdarg.h.
Failed to get including location of include stdint.h.
Failed to get including location of include stdio.h.
Failed to get including location of include stdlib.h.
Failed to get including location of include wchar.h.
Failed to get including location of include xmmintrin.h.
File unspecified
Error while performing static analysis.
java.lang.NullPointerException

I am assuming that it isn't a problem that the system headers can't be located. 

I have changed my vmargs to include:
-Xms1024m
-Xmx8192m

Is there any way to learn specifically what the issue is (I may be able to work around it if I understand what the problem is).

**Comment by PeterSommerlad** [comment] 2017-04-15 08:12
Sorry over the Easter holidays you might not get a substantial support. But you can open the error log view, select and copy paste the corresponding stack trace here which might give an indication which checker (assuming static analysis is really the reason for the npe) is guilty. A second option is to check the JVM's/Eclipse memory usage( I know there must be a plugin for it) to see if even with your settings the JVM runs out of usable memory making allocations fail. A third option might be, that the OS limits the numbers of open files below what is needed or the files lack permissions, because you get messages related to file access.

**Comment by tcorbat** [comment] 2017-04-18 08:33
@rtosman We're back from our Easter holidays. Thanks for your report!

Is there a more detailed stack track in the Eclipse Error Log? It would be helpful to know where exactly this NPE occured. I guess you cannot provide a minimal example to reproduce the issue, right?

**Comment by fmorgner** [comment] 2017-04-18 12:22
I have found 2 NPEs. I was able to create a minimal example for the second one.

### Steps to reproduce:

1. Create a new C++ project in Cevelop
2. Add the following two files (They have to be two separate files!):

    - GH17ClassNPE.h:
    ```c++
    #ifndef GH17_CLASS_NPE
    #define GH17_CLASS_NPE
    
    class GH17ClassNPE: public GH17ClassNPEBase { // The base must not exist!
	    GH17ClassNPE();
    };
    #endif
    ```

    - GH17ClassNPE.cpp:
    ```c++
    #include "GH17ClassNPE.h"
    
    GH17ClassNPE::GH17ClassNPE() : GH17ClassNPEBase { } {
    }
    ```

3. Run Includator "Organize Includes" on either the Project or the CPP file (This is important since running it on the header will not produce the NPE)

### Stacktrace:
```
java.lang.NullPointerException
	at com.cevelop.includator.helpers.ConstructorReferenceHelper.findImplicitlyInitializedBaseClasses(ConstructorReferenceHelper.java:78)
	at com.cevelop.includator.helpers.ConstructorReferenceHelper.addImplicitBaseClassConstructors(ConstructorReferenceHelper.java:49)
	at com.cevelop.includator.helpers.DeclarationReferenceVisitor.performAdditionalRefActions(DeclarationReferenceVisitor.java:213)
	at com.cevelop.includator.helpers.DeclarationReferenceVisitor.addName(DeclarationReferenceVisitor.java:159)
	at com.cevelop.includator.helpers.DeclarationReferenceVisitor.visit(DeclarationReferenceVisitor.java:81)
	at org.eclipse.cdt.internal.core.dom.parser.cpp.CPPASTName.accept(CPPASTName.java:150)
	at org.eclipse.cdt.internal.core.dom.parser.cpp.CPPASTQualifiedName.accept(CPPASTQualifiedName.java:247)
	at org.eclipse.cdt.internal.core.dom.parser.cpp.CPPASTDeclarator.accept(CPPASTDeclarator.java:190)
	at org.eclipse.cdt.internal.core.dom.parser.cpp.CPPASTFunctionDefinition.accept(CPPASTFunctionDefinition.java:204)
	at org.eclipse.cdt.internal.core.dom.parser.ASTTranslationUnit.accept(ASTTranslationUnit.java:266)
	at com.cevelop.includator.helpers.DeclarationReferenceHelper.findDeclReferences(DeclarationReferenceHelper.java:54)
	at com.cevelop.includator.resources.IncludatorFile.getDeclarationReferences(IncludatorFile.java:60)
	at com.cevelop.includator.optimizer.findunusedincludes.FindUnusedIncludesAlgorithm.run(FindUnusedIncludesAlgorithm.java:55)
	at com.cevelop.includator.optimizer.Algorithm.start(Algorithm.java:42)
	at com.cevelop.includator.optimizer.ScopedAlgorithm.run(ScopedAlgorithm.java:34)
	at com.cevelop.includator.optimizer.Algorithm.start(Algorithm.java:42)
	at com.cevelop.includator.optimizer.Optimizer.run(Optimizer.java:37)
	at com.cevelop.includator.ui.OptimizationRunner.run(OptimizationRunner.java:57)
	at com.cevelop.includator.ui.actions.IncludatorAlgorithmAction.runAnalysisJob(IncludatorAlgorithmAction.java:110)
	at com.cevelop.includator.ui.actions.IncludatorAlgorithmAction$1.runWithWorkbenchWindow(IncludatorAlgorithmAction.java:58)
	at com.cevelop.includator.ui.actions.IncludatorJob.run(IncludatorJob.java:32)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
```

### Notes

A similar NPE happens in relation to non-static member functions, but I am currently no able to reproduce it using a minimal example. For both of them, I have a preliminary fix on my own branch.

**Comment by fmorgner** [comment] 2017-04-19 07:44
Moved the NPE issue to #22 since it is not related to the release process. Closing this issue, since 1.7.0 has been released. Any further information shall be attached to #22. Thanks for reporting the issue!

**Closed as completed by fmorgner** 2017-04-19 07:44 UTC
